
import { test, expect } from '@playwright/test';

test('This was a generated by codegen', async ({ page }) => {
  await page.goto('https://the-internet.herokuapp.com/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('tomsmith');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('SuperSecretPassword!');
  await page.getByRole('button', { name: ' Login' }).click();
  await expect(page.getByText('You logged into a secure area')).toBeVisible();
  await expect(page.locator('h4')).toContainText('Welcome to the Secure Area. When you are done click logout below.');
  await expect(page.locator('body')).toMatchAriaSnapshot(`
    - text:  You logged into a secure area!
    - link "×"
    - link "Fork me on GitHub":
      - img "Fork me on GitHub"
    - heading "Secure Area" [level=2]
    - heading "Welcome to the Secure Area. When you are done click logout below." [level=4]
    - link "Logout"
    - separator
    - text: Powered by
    - link "Elemental Selenium"
    `);
  await page.getByRole('link', { name: 'Logout' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('11');
  await expect(page.getByRole('textbox', { name: 'Username' })).toHaveValue('11');
});